### PR TITLE
iOS issue: fixed race condition

### PR DESCRIPTION
**Pull request by lpschz**
This solves a race condition that affects mostly iOS.

Apparently, the code would try to select and insert values in `dbVersions` before this was created, there was a race condition. Solution was to include this logic on the callback of creating `dbVersions`

### CODE REVIEW

**Comment by raulsouzalima** [comment]
@axemclion any thoughts about it?

**Comment by DickvdBrink** [comment]
I think @BigstickCarpet already fixed it in the latest version, the new code in dist looks correct so I think we can close this one. 
Or are you still seeing a issue with the latest code?

**Comment by raulsouzalima** [comment]
I think so! I'm using the 2.0.4 and testing on iphone 4s with ios 8.4.

When the code try to create the dbVersions, returns an error "could not prepare statement (1 not authorized)"

**Comment by brettz9** [comment]
This particular race condition is already handled in code.  While there are a number of iOS related issues reported (possibly interrelated) and I'm not sure why you'd be seeing that problem, @raulsouzalima (especially since someone else reported the same error in #144 which has apparently since been fixed), I think I will close this PR and invite you to open a new issue (or PR to fix) if you are still seeing the issue.

**Pull request closed without merging**
