### PR TITLE
Quote index names

### PR DESCRIPTION
**Pull request by pixel9**
Quoting index names when generating SQL so we don't trip up on index names with spaces and dots.

Tests updated, which caught one more spot I missed in my earlier PR!

### CODE REVIEW

**Comment by pixel9** [comment]
I went ahead and rebased this against the latest changes in master.

**Comment by JamesMessinger** [comment]
Thanks for all your help lately.   It's very much appreciated!

**Comment by pixel9** [comment]
Thank you for maintaining this project! I'm just glad I'm able to contribute something back to a project that's been very helpful. 

At the pace you're going, I'm assuming you're knee deep refactoring IDBCursor stuff. Should I hold off on the rest of [this PR](https://github.com/axemclion/IndexedDBShim/pull/186)?

**Comment by JamesMessinger** [comment]
I just pushed version 1.0.5, which fixes a bunch of bugs with `IDBCursor` and `IDBKeyRange`.   I've created a [unit test for multi-entry cursors](https://github.com/axemclion/IndexedDBShim/blob/master/tests/IDBIndex/openCursor-spec.js#L757).  It passes in all _native_ IndexedDB implementations, but not yet with IndexedDBShim.   Feel free to take a stab at it if you want.  I'm calling it quits for today, and will probably be too busy to get to it tomorrow.

**Comment by pixel9** [comment]
I'll re-attempt it then. Thanks for the test!

**Pull request merged**
