### PR TITLE
Add multiEntry support to IDBCursor

### PR DESCRIPTION
**Pull request by pixel9**
This PR adds lowerBound support for using an IDBCursor against a multiEntry index.

There is also a minor fix included that addresses using a cursor with an index that contains dots/spaces. I can split that out into a separate PR/issue if desired.

Thanks!

### CODE REVIEW

**Comment by pixel9** [comment]
Closing. I'll re-submit after adding tests.

**Comment by JamesMessinger** [comment]
Cool.  Thanks for tackling this.  And yes, it definitely warrants having some unit tests. Most of the [`IDBIndex.get()` unit tests](https://github.com/axemclion/IndexedDBShim/blob/master/tests/IDBIndex/get-spec.js) should also apply to cursors.

Ideally, there should be a lot of reusable code between [`IDBIndex.js`](https://github.com/axemclion/IndexedDBShim/blob/master/src/IDBIndex.js) and [`IDBCursor.js`](https://github.com/axemclion/IndexedDBShim/blob/master/src/IDBCursor.js).  Feel free to refactor either/both of them to share as much common code as possible.

**Comment by pixel9** [comment]
Gotcha. I'll probably split the bug fix apart from this PR as a separate request (with some tests) and tackle the multientry support in a separate PR.

**Comment by JamesMessinger** [comment]
Ok, that works.  I'm about to start working on refactoring IDBCursor anyway, but I need to write some tests for it first.  hooray for TDD :)

**Comment by pixel9** [comment]
Cool, it would be nice to have full support for multiEntry for cursors. I'll just use my temporary solution locally until you're done :)

**Pull request closed without merging**
