### PR TITLE
when encoding key that is null, return null

### PR DESCRIPTION
**Pull request by zawaideh**
ran into this problem when having a key that can be null.

### CODE REVIEW

**Comment by brody2consult** [comment]
Suggestion on my part to add a test case, if possible.

**Comment by zawaideh** [comment]
Is there a unit test file for Key? Not that familiar with the codebase, if I point me to where you are thinking the test case should go, I'd be happy to add it.

**Comment by brettz9** [comment]
I've adapted this PR and incorporated it into `master`. Feel free to comment further, add a new bug, etc. if you find any new issues. With the W3C tests just added, we can hopefully improve quality even further. See also #238

**Comment by brettz9** [comment]
Sorry, I was premature in adding my code. Please pull again from `master` if you've already updated, as I've fixed things to either throw a proper error or silently ignore, as per spec behavior. Please see my comment at https://github.com/axemclion/IndexedDBShim/issues/215#issuecomment-227218203 .

**Pull request closed without merging**
