### PR TITLE
Fix: Make references to websql using module id instead of by path

### PR DESCRIPTION
**Pull request by erikvold**

### CODE REVIEW

**Comment by brettz9** [comment]
Aha... Good find, thanks! Aim to get to this shortly...

**Comment by erikvold** [comment]
Hmm actually I think I was mistaken, this patch doesn't seem to resolve the error I was getting in https://github.com/axemclion/IndexedDBShim/issues/259#issuecomment-279206410

**Comment by brettz9** [comment]
I did incorporate your change, but I think I might have added the relative path myself due to this approach not working either. :) I would think your approach would work as it is a dependency of thisone...Anyways closing this but if you find another fix, feel free to make a new PR or overwrite this one.

**Comment by brettz9** [comment]
Should truly be fixed now in `master` (as discussed in #262).

**Pull request closed without merging**
