### PR TITLE
Add shimIndexedDB.__unuseShim()

### PR DESCRIPTION
**Pull request by bolasblack**
I need migrate data from `IndexedDBShim` to `indexedDB`.

So I hope I can call `__useShim()` export all data from `IndexedDBShim`, then call `__unuseShim()` and import them to the real `indexedDB`.

### CODE REVIEW

**Comment by axemclion** [comment]
Should this be a part of the library ? IMHO, this could be a script that you run before importing the shim. Then you could reassign the constants.

I think it would make sense to publish this as a separate library instead of making the function available as a part of the shim. We could also link to the "unshimming" library from the README.

**Comment by bolasblack** [comment]
Hmmmmm... I think you are right! Thank you! :P

**Comment by axemclion** [comment]
@bolasblack Thanks for the PR though, I did not mean to prevent it from being merged. I just thought that it would make sense as a separate library. If you believe that it should be a part of this, you should re-open and we could let other contributors chime in.

**Comment by bolasblack** [comment]
@axemclion I agree with you, about unshimming, it's not a necessary function and users can implement it out of IndexedDBShim, so I think it's no need to be a part of the library.

**Pull request closed without merging**
