### PR TITLE
Support multiEntry index in IDBCursor

### PR DESCRIPTION
**Pull request by pixel9**
I've isolated the code to support multiEntry as much as possible to minimize any potential impact to existing cursor behavior.

My gut tells me the `isKeyInRange` and the sorting algorithms can be improved but everything seems to work well now.

### CODE REVIEW

**Comment by pixel9** [comment]
Rebased against master. Ran a bunch of integration tests in a real-world app and works great!

**Comment by JamesMessinger** [comment]
Sorry I haven't had time to merge this yet.  Been super busy at work.  :-/     I'll try to take a look at it today or tomorrow and get it merged in.

Thanks for all your contribs!  This is great stuff!

**Comment by pixel9** [comment]
No worries! I just wanted to keep this ready to go to save you some time.

**Comment by JamesMessinger** [comment]
Alright, I just tested it on all the different devices & browsers, and it works great!   You rock, sir!  Thanks for getting this done.

I'll release a new version to NPM and update the Cordova plugins later today.

**Comment by pixel9** [comment]
Glad I could help!

**Pull request merged**
