### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by brettz9**
Convert JSHint to ESLint and lint;
Lint package.json;
Lint markdown with Remark and lint;
Trim WS

I'm looking to make some more substantive changes, but I think it will be better to have ESLint, etc. as per the PR.

### CODE REVIEW

**Comment by brettz9** [comment]
In this PR I tried to stick to mostly just replicating your old settings.

The one area I did not go through linting but thought should be added to the linting process were the tests, but they'd require more substantial changes to move away from the `expect(...).to.be.undefined` format (which triggers "unused expression" warnings). Let me know if you'd be ok with that.

**Comment by axemclion** [comment]
@brettz9 Thanks - this looks like a big PR, I will start reviewing it now.

**Comment by brettz9** [comment]
Big yes, but mostly just required whitespace changes...

**Comment by brettz9** [comment]
In case you want to wait and review all major changes in one PR, I do have more big but minor changes coming down the pipeline, namely changing away from your own custom module system (and from use of globals) to using ES6 modules (converted with Babel and browserify) both for the sake of providing a more standard and familiar means of indicating dependencies, and also since I want to import other dependencies anyways (including code that I have ready for Node support). I also have code ready for upgrading to QUnit 2.0 syntax.

Although this PR does not do so, I also wanted to enforce more consistent styling (e.g., always single quotes), and possibly even convert to http://standardjs.com/ (and some stricter ES6 rules, like using const or let as possible) if you are open to it (which is helpful not only for consistent styling across projects, but also because its ESLint form allows for stricter rule enforcement).

Please let me know so I can do the remaining work of preparing an update to this PR or a new PR on top of this one, as you prefer. Thanks!

**Pull request merged**
